
const CHELSEA_CLUB_ID = 631
const PREMIER_LEAGUE_COMP_ID = "'GB1'"
const CHELSEA_VS_ARSENAL_GAME_ID = 2258986
const MANCHESTER_UNITED_CLUB_ID =  985

module.exports = {
    CHELSEA_CLUB_ID,
    PREMIER_LEAGUE_COMP_ID,
    CHELSEA_VS_ARSENAL_GAME_ID,
    MANCHESTER_UNITED_CLUB_ID,
}