// GENERATED FILE - DO NOT EDIT.
// Generated by scripts/generate-config-schema.mjs from @dataform/core@3.0.71 configs.proto.
// Regenerate with: npm run generate:config-schema

export interface ProtoField {
    name: string;
    /** Proto scalar type, a message/enum name, or "map" for map<string, string> fields. */
    type: string;
    repeated: boolean;
    doc: string;
}

export interface ProtoEnumValue {
    name: string;
    doc: string;
}

export const CONFIG_SCHEMA_CORE_VERSION = "3.0.71";

export const protoMessages: Record<string, ProtoField[]> = {
    "WorkflowSettings": [
        {
            "name": "dataformCoreVersion",
            "type": "string",
            "repeated": false,
            "doc": "The desired dataform core version to compile against."
        },
        {
            "name": "defaultProject",
            "type": "string",
            "repeated": false,
            "doc": "Required. The default Google Cloud project (database)."
        },
        {
            "name": "defaultDataset",
            "type": "string",
            "repeated": false,
            "doc": "Required. The default dataset (schema)."
        },
        {
            "name": "defaultLocation",
            "type": "string",
            "repeated": false,
            "doc": "Required. The default BigQuery location to use. For more information on BigQuery locations, see https://cloud.google.com/bigquery/docs/locations."
        },
        {
            "name": "defaultAssertionDataset",
            "type": "string",
            "repeated": false,
            "doc": "Required. The default dataset (schema) for assertions."
        },
        {
            "name": "vars",
            "type": "map",
            "repeated": false,
            "doc": "Optional. User-defined variables that are made available to project code during compilation. An object containing a list of \"key\": value pairs."
        },
        {
            "name": "projectSuffix",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The suffix to append to all Google Cloud project references."
        },
        {
            "name": "datasetSuffix",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The suffix to append to all dataset references."
        },
        {
            "name": "namePrefix",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The prefix to append to all action names."
        },
        {
            "name": "defaultNotebookRuntimeOptions",
            "type": "NotebookRuntimeOptionsConfig",
            "repeated": false,
            "doc": "Optional. Default runtime options for Notebook actions."
        },
        {
            "name": "builtinAssertionNamePrefix",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The prefix to append to built-in assertion names."
        },
        {
            "name": "defaultIcebergConfig",
            "type": "DefaultIcebergConfig",
            "repeated": false,
            "doc": "Optional. Default config options for Iceberg tables."
        },
        {
            "name": "disableAssertions",
            "type": "bool",
            "repeated": false,
            "doc": "Optional. Disables all assertions including built-in assertions (uniqueKey, nonNull, rowConditions) and manual assertions (type: assertion). When true, assertions will still be compiled but marked as disabled."
        },
        {
            "name": "defaultReservation",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The default BigQuery reservation to use for execution. If unset, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending)."
        },
        {
            "name": "extension",
            "type": "Extension",
            "repeated": false,
            "doc": "Optional. An external package that provides an extension."
        },
        {
            "name": "includeTestsInCompiledGraph",
            "type": "bool",
            "repeated": false,
            "doc": "Optional. If set to true, unit tests will be included in the compiled graph."
        },
        {
            "name": "preserveGovernanceControls",
            "type": "bool",
            "repeated": false,
            "doc": "Optional. If set to true, governance controls (e.g. Data Policies) will be preserved on BigQuery tables."
        },
        {
            "name": "lineage",
            "type": "LineageSettings",
            "repeated": false,
            "doc": "Optional. Configuration for Knowledge Catalog lineage emission."
        }
    ],
    "LineageSettings": [
        {
            "name": "enabled",
            "type": "bool",
            "repeated": false,
            "doc": "If true, downstream runners will emit OpenLineage events to Knowledge Catalog for actions executed from this project."
        }
    ],
    "ActionConfigs": [
        {
            "name": "actions",
            "type": "ActionConfig",
            "repeated": true,
            "doc": ""
        }
    ],
    "ActionConfig": [
        {
            "name": "table",
            "type": "TableConfig",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "view",
            "type": "ViewConfig",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "incrementalTable",
            "type": "IncrementalTableConfig",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "assertion",
            "type": "AssertionConfig",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "operation",
            "type": "OperationConfig",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "declaration",
            "type": "DeclarationConfig",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "notebook",
            "type": "NotebookConfig",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "dataPreparation",
            "type": "DataPreparationConfig",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "propertyGraph",
            "type": "PropertyGraphConfig",
            "repeated": false,
            "doc": ""
        }
    ],
    "ActionConfig.Target": [
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the action."
        },
        {
            "name": "dataset",
            "type": "string",
            "repeated": false,
            "doc": "The dataset (schema) of the action. For notebooks, this is the location."
        },
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the action."
        },
        {
            "name": "includeDependentAssertions",
            "type": "bool",
            "repeated": false,
            "doc": "flag for when we want to add assertions of this dependency in dependency_targets as well."
        }
    ],
    "ActionConfig.ColumnDescriptor": [
        {
            "name": "path",
            "type": "string",
            "repeated": true,
            "doc": "The identifier for the column, using multiple parts for nested records."
        },
        {
            "name": "description",
            "type": "string",
            "repeated": false,
            "doc": "A text description of the column."
        },
        {
            "name": "bigqueryPolicyTags",
            "type": "string",
            "repeated": true,
            "doc": "A list of BigQuery policy tags that will be applied to the column."
        },
        {
            "name": "tags",
            "type": "string",
            "repeated": true,
            "doc": "A list of tags for this column which will be applied."
        }
    ],
    "ActionConfig.TableAssertionsConfig": [
        {
            "name": "uniqueKey",
            "type": "string",
            "repeated": true,
            "doc": "Column(s) which constitute the dataset's unique key index. If set, the resulting assertion will fail if there is more than one row in the dataset with the same values for all of these column(s)."
        },
        {
            "name": "uniqueKeys",
            "type": "UniqueKey",
            "repeated": true,
            "doc": ""
        },
        {
            "name": "nonNull",
            "type": "string",
            "repeated": true,
            "doc": "Column(s) which may never be `NULL`. If set, the resulting assertion will fail if any row contains `NULL` values for these column(s)."
        },
        {
            "name": "rowConditions",
            "type": "string",
            "repeated": true,
            "doc": "General condition(s) which should hold true for all rows in the dataset. If set, the resulting assertion will fail if any row violates any of these condition(s)."
        }
    ],
    "ActionConfig.TableAssertionsConfig.UniqueKey": [
        {
            "name": "uniqueKey",
            "type": "string",
            "repeated": true,
            "doc": ""
        }
    ],
    "ActionConfig.IcebergTableConfig": [
        {
            "name": "fileFormat",
            "type": "FileFormat",
            "repeated": false,
            "doc": "The file format for the BigQuery table."
        },
        {
            "name": "connection",
            "type": "string",
            "repeated": false,
            "doc": "The connection specifying the credentials to be used to read and write to external storage, such as Cloud Storage. The connection can have the form `{project}.{location}.{connection_id}` or `projects/{project}/locations/{location}/connections/{connection_id}\", or be set to DEFAULT."
        },
        {
            "name": "bucketName",
            "type": "string",
            "repeated": false,
            "doc": "The name of the Cloud Storage bucket where table data is stored. This value is be used to construct the storage URI in the following way: `gs://{bucket_name}/{table_folder_root}/{table_folder_subpath}``. If `storage_uri` is provided, this value is ignored."
        },
        {
            "name": "tableFolderRoot",
            "type": "string",
            "repeated": false,
            "doc": "The name of the first-level folder inside the Cloud Storage bucket where table data is stored. This value will be used to construct the storage URI in the following way: `gs://{bucket_name}/{table_folder_root}/{table_folder_subpath}``. If `storage_uri` is provided, this value is ignored."
        },
        {
            "name": "tableFolderSubpath",
            "type": "string",
            "repeated": false,
            "doc": "The path under the first-level folder of the Cloud Storage bucket where table data is stored. This value will be used to construct the storage URI in the following way: `gs://{bucket_name}/{table_folder_root}/{table_folder_subpath}``. If `storage_uri` is provided, this value is ignored."
        }
    ],
    "ActionConfig.TableConfig": [
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the table."
        },
        {
            "name": "dataset",
            "type": "string",
            "repeated": false,
            "doc": "The dataset (schema) of the table."
        },
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the table."
        },
        {
            "name": "dependencyTargets",
            "type": "Target",
            "repeated": true,
            "doc": "Targets of actions that this action is dependent on."
        },
        {
            "name": "filename",
            "type": "string",
            "repeated": false,
            "doc": "Path to the source file that the contents of the action is loaded from."
        },
        {
            "name": "tags",
            "type": "string",
            "repeated": true,
            "doc": "A list of user-defined tags with which the action should be labeled."
        },
        {
            "name": "disabled",
            "type": "bool",
            "repeated": false,
            "doc": "If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions."
        },
        {
            "name": "preOperations",
            "type": "string",
            "repeated": true,
            "doc": "Queries to run before `query`. This can be useful for granting permissions."
        },
        {
            "name": "postOperations",
            "type": "string",
            "repeated": true,
            "doc": "Queries to run after `query`."
        },
        {
            "name": "description",
            "type": "string",
            "repeated": false,
            "doc": "Description of the table."
        },
        {
            "name": "columns",
            "type": "ColumnDescriptor",
            "repeated": true,
            "doc": "Descriptions of columns within the table."
        },
        {
            "name": "partitionBy",
            "type": "string",
            "repeated": false,
            "doc": "The key by which to partition the table. Typically the name of a timestamp or the date column. See https://cloud.google.com/dataform/docs/partitions-clusters."
        },
        {
            "name": "partitionExpirationDays",
            "type": "int32",
            "repeated": false,
            "doc": "The number of days for which BigQuery stores data in each partition. The setting applies to all partitions in a table, but is calculated independently for each partition based on the partition time."
        },
        {
            "name": "requirePartitionFilter",
            "type": "bool",
            "repeated": false,
            "doc": "Declares whether the partitioned table requires a WHERE clause predicate filter that filters the partitioning column."
        },
        {
            "name": "clusterBy",
            "type": "string",
            "repeated": true,
            "doc": "The keys by which to cluster partitions by. See https://cloud.google.com/dataform/docs/partitions-clusters."
        },
        {
            "name": "labels",
            "type": "map",
            "repeated": false,
            "doc": "Key-value pairs for BigQuery labels."
        },
        {
            "name": "additionalOptions",
            "type": "map",
            "repeated": false,
            "doc": "Key-value pairs of additional options to pass to the BigQuery API. Some options, for example, partitionExpirationDays, have dedicated type/validity checked fields. For such options, use the dedicated fields."
        },
        {
            "name": "dependOnDependencyAssertions",
            "type": "bool",
            "repeated": false,
            "doc": "When set to true, assertions dependent upon any dependency will be add as dedpendency to this action"
        },
        {
            "name": "assertions",
            "type": "TableAssertionsConfig",
            "repeated": false,
            "doc": "Assertions to be run on the dataset. If configured, relevant assertions will automatically be created and run as a dependency of this dataset."
        },
        {
            "name": "hermetic",
            "type": "bool",
            "repeated": false,
            "doc": "If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the action depends on data from a source which has not been declared as a dependency."
        },
        {
            "name": "iceberg",
            "type": "IcebergTableConfig",
            "repeated": false,
            "doc": "Configuration options for an Iceberg table."
        },
        {
            "name": "metadata",
            "type": "Metadata",
            "repeated": false,
            "doc": "Metadata for this table."
        },
        {
            "name": "reservation",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending)."
        },
        {
            "name": "preserveGovernanceControls",
            "type": "bool",
            "repeated": false,
            "doc": "Optional. If true, preserves existing BigQuery column governance controls (e.g. data policy) when recreating a table."
        }
    ],
    "ActionConfig.Metadata": [
        {
            "name": "overview",
            "type": "string",
            "repeated": false,
            "doc": "A detailed description of the data object."
        },
        {
            "name": "extraProperties",
            "type": "google.protobuf.Struct",
            "repeated": false,
            "doc": "Extra properties of the data object."
        }
    ],
    "ActionConfig.ViewConfig": [
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the view."
        },
        {
            "name": "dataset",
            "type": "string",
            "repeated": false,
            "doc": "The dataset (schema) of the view."
        },
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the view."
        },
        {
            "name": "dependencyTargets",
            "type": "Target",
            "repeated": true,
            "doc": "Targets of actions that this action is dependent on."
        },
        {
            "name": "filename",
            "type": "string",
            "repeated": false,
            "doc": "Path to the source file that the contents of the action is loaded from."
        },
        {
            "name": "tags",
            "type": "string",
            "repeated": true,
            "doc": "A list of user-defined tags with which the action should be labeled."
        },
        {
            "name": "disabled",
            "type": "bool",
            "repeated": false,
            "doc": "If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions."
        },
        {
            "name": "preOperations",
            "type": "string",
            "repeated": true,
            "doc": "Queries to run before `query`. This can be useful for granting permissions."
        },
        {
            "name": "postOperations",
            "type": "string",
            "repeated": true,
            "doc": "Queries to run after `query`."
        },
        {
            "name": "materialized",
            "type": "bool",
            "repeated": false,
            "doc": "Applies the materialized view optimization, see https://cloud.google.com/bigquery/docs/materialized-views-intro."
        },
        {
            "name": "partitionBy",
            "type": "string",
            "repeated": false,
            "doc": "Optional. Applicable only to materialized view. The key by which to partition the materialized view. Typically the name of a timestamp or the date column. See https://cloud.google.com/bigquery/docs/materialized-views-create#partitioned_materialized_views."
        },
        {
            "name": "clusterBy",
            "type": "string",
            "repeated": true,
            "doc": "Optional. Applicable only to materialized view. The keys by which to cluster partitions by. See https://cloud.google.com/bigquery/docs/materialized-views-create#cluster_materialized_views."
        },
        {
            "name": "description",
            "type": "string",
            "repeated": false,
            "doc": "Description of the view."
        },
        {
            "name": "columns",
            "type": "ColumnDescriptor",
            "repeated": true,
            "doc": "Descriptions of columns within the table."
        },
        {
            "name": "labels",
            "type": "map",
            "repeated": false,
            "doc": "Key-value pairs for BigQuery labels."
        },
        {
            "name": "additionalOptions",
            "type": "map",
            "repeated": false,
            "doc": "Key-value pairs of additional options to pass to the BigQuery API. Some options, for example, partitionExpirationDays, have dedicated type/validity checked fields. For such options, use the dedicated fields."
        },
        {
            "name": "dependOnDependencyAssertions",
            "type": "bool",
            "repeated": false,
            "doc": "When set to true, assertions dependent upon any dependency will be add as dedpendency to this action"
        },
        {
            "name": "hermetic",
            "type": "bool",
            "repeated": false,
            "doc": "If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the action depends on data from a source which has not been declared as a dependency."
        },
        {
            "name": "assertions",
            "type": "TableAssertionsConfig",
            "repeated": false,
            "doc": "Assertions to be run on the dataset. If configured, relevant assertions will automatically be created and run as a dependency of this dataset."
        },
        {
            "name": "metadata",
            "type": "Metadata",
            "repeated": false,
            "doc": "Metadata for this view."
        },
        {
            "name": "reservation",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending)."
        }
    ],
    "ActionConfig.IncrementalTableConfig": [
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the incremental table."
        },
        {
            "name": "dataset",
            "type": "string",
            "repeated": false,
            "doc": "The dataset (schema) of the incremental table."
        },
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the incremental table."
        },
        {
            "name": "dependencyTargets",
            "type": "Target",
            "repeated": true,
            "doc": "Targets of actions that this action is dependent on."
        },
        {
            "name": "filename",
            "type": "string",
            "repeated": false,
            "doc": "Path to the source file that the contents of the action is loaded from."
        },
        {
            "name": "tags",
            "type": "string",
            "repeated": true,
            "doc": "A list of user-defined tags with which the action should be labeled."
        },
        {
            "name": "disabled",
            "type": "bool",
            "repeated": false,
            "doc": "If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions."
        },
        {
            "name": "preOperations",
            "type": "string",
            "repeated": true,
            "doc": "Queries to run before `query`. This can be useful for granting permissions."
        },
        {
            "name": "postOperations",
            "type": "string",
            "repeated": true,
            "doc": "Queries to run after `query`."
        },
        {
            "name": "protected",
            "type": "bool",
            "repeated": false,
            "doc": "If true, prevents the dataset from being rebuilt from scratch."
        },
        {
            "name": "uniqueKey",
            "type": "string",
            "repeated": true,
            "doc": "If set, unique key represents a set of names of columns that will act as a the unique key. To enforce this, when updating the incremental table, Dataform merges rows with `uniqueKey` instead of appending them."
        },
        {
            "name": "description",
            "type": "string",
            "repeated": false,
            "doc": "Description of the incremental table."
        },
        {
            "name": "columns",
            "type": "ColumnDescriptor",
            "repeated": true,
            "doc": "Descriptions of columns within the table."
        },
        {
            "name": "partitionBy",
            "type": "string",
            "repeated": false,
            "doc": "The key by which to partition the table. Typically the name of a timestamp or the date column. See https://cloud.google.com/dataform/docs/partitions-clusters."
        },
        {
            "name": "partitionExpirationDays",
            "type": "int32",
            "repeated": false,
            "doc": "The number of days for which BigQuery stores data in each partition. The setting applies to all partitions in a table, but is calculated independently for each partition based on the partition time."
        },
        {
            "name": "requirePartitionFilter",
            "type": "bool",
            "repeated": false,
            "doc": "Declares whether the partitioned table requires a WHERE clause predicate filter that filters the partitioning column."
        },
        {
            "name": "updatePartitionFilter",
            "type": "string",
            "repeated": false,
            "doc": "SQL-based filter for when incremental updates are applied."
        },
        {
            "name": "clusterBy",
            "type": "string",
            "repeated": true,
            "doc": "The keys by which to cluster partitions by. See https://cloud.google.com/dataform/docs/partitions-clusters."
        },
        {
            "name": "labels",
            "type": "map",
            "repeated": false,
            "doc": "Key-value pairs for BigQuery labels."
        },
        {
            "name": "additionalOptions",
            "type": "map",
            "repeated": false,
            "doc": "Key-value pairs of additional options to pass to the BigQuery API. Some options, for example, partitionExpirationDays, have dedicated type/validity checked fields. For such options, use the dedicated fields."
        },
        {
            "name": "dependOnDependencyAssertions",
            "type": "bool",
            "repeated": false,
            "doc": "When set to true, assertions dependent upon any dependency will be add as dedpendency to this action"
        },
        {
            "name": "assertions",
            "type": "TableAssertionsConfig",
            "repeated": false,
            "doc": "Assertions to be run on the dataset. If configured, relevant assertions will automatically be created and run as a dependency of this dataset."
        },
        {
            "name": "hermetic",
            "type": "bool",
            "repeated": false,
            "doc": "If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the action depends on data from a source which has not been declared as a dependency."
        },
        {
            "name": "onSchemaChange",
            "type": "OnSchemaChange",
            "repeated": false,
            "doc": "Defines the action behavior if the selected columns in the query don't the match columns in the target table."
        },
        {
            "name": "iceberg",
            "type": "IcebergTableConfig",
            "repeated": false,
            "doc": "Configuration options for an Iceberg table."
        },
        {
            "name": "metadata",
            "type": "Metadata",
            "repeated": false,
            "doc": "Metadata for this incremental table."
        },
        {
            "name": "reservation",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending)."
        },
        {
            "name": "incrementalStrategy",
            "type": "IncrementalStrategy",
            "repeated": false,
            "doc": "Optional. The incremental strategy to use when updating the table."
        },
        {
            "name": "incrementalPredicates",
            "type": "string",
            "repeated": true,
            "doc": "Array of SQL-based predicates for when incremental updates are applied."
        },
        {
            "name": "preserveGovernanceControls",
            "type": "bool",
            "repeated": false,
            "doc": "Optional. If true, preserves existing BigQuery column governance controls (e.g. data policy) when recreating a table."
        }
    ],
    "ActionConfig.AssertionConfig": [
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the assertion."
        },
        {
            "name": "dataset",
            "type": "string",
            "repeated": false,
            "doc": "The dataset (schema) of the assertion."
        },
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the assertion."
        },
        {
            "name": "dependencyTargets",
            "type": "Target",
            "repeated": true,
            "doc": "Targets of actions that this action is dependent on."
        },
        {
            "name": "filename",
            "type": "string",
            "repeated": false,
            "doc": "Path to the source file that the contents of the action is loaded from."
        },
        {
            "name": "tags",
            "type": "string",
            "repeated": true,
            "doc": "A list of user-defined tags with which the action should be labeled."
        },
        {
            "name": "disabled",
            "type": "bool",
            "repeated": false,
            "doc": "If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions."
        },
        {
            "name": "description",
            "type": "string",
            "repeated": false,
            "doc": "Description of the assertion."
        },
        {
            "name": "hermetic",
            "type": "bool",
            "repeated": false,
            "doc": "If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the action depends on data from a source which has not been declared as a dependency."
        },
        {
            "name": "dependOnDependencyAssertions",
            "type": "bool",
            "repeated": false,
            "doc": "If true, assertions dependent upon any of the dependencies are added as dependencies as well."
        },
        {
            "name": "reservation",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending)."
        },
        {
            "name": "metadata",
            "type": "Metadata",
            "repeated": false,
            "doc": "Metadata for this assertion."
        }
    ],
    "ActionConfig.OperationConfig": [
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the operation."
        },
        {
            "name": "dataset",
            "type": "string",
            "repeated": false,
            "doc": "The dataset (schema) of the operation."
        },
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the operation."
        },
        {
            "name": "dependencyTargets",
            "type": "Target",
            "repeated": true,
            "doc": "Targets of actions that this action is dependent on."
        },
        {
            "name": "filename",
            "type": "string",
            "repeated": false,
            "doc": "Path to the source file that the contents of the action is loaded from."
        },
        {
            "name": "tags",
            "type": "string",
            "repeated": true,
            "doc": "A list of user-defined tags with which the action should be labeled."
        },
        {
            "name": "disabled",
            "type": "bool",
            "repeated": false,
            "doc": "If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions."
        },
        {
            "name": "hasOutput",
            "type": "bool",
            "repeated": false,
            "doc": "Declares that this action creates a dataset which should be referenceable as a dependency target, for example by using the `ref` function."
        },
        {
            "name": "description",
            "type": "string",
            "repeated": false,
            "doc": "Description of the operation."
        },
        {
            "name": "columns",
            "type": "ColumnDescriptor",
            "repeated": true,
            "doc": "Descriptions of columns within the operation. Can only be set if hasOutput is true."
        },
        {
            "name": "dependOnDependencyAssertions",
            "type": "bool",
            "repeated": false,
            "doc": "When set to true, assertions dependent upon any dependency will be add as dedpendency to this action"
        },
        {
            "name": "hermetic",
            "type": "bool",
            "repeated": false,
            "doc": "If true, this indicates that the action only depends on data from explicitly-declared dependencies. Otherwise if false, it indicates that the action depends on data from a source which has not been declared as a dependency."
        },
        {
            "name": "reservation",
            "type": "string",
            "repeated": false,
            "doc": "Optional. The BigQuery reservation to use for execution. If unset, the value from workflow_settings.yaml is used. If neither is set, default BigQuery behavior applies. Dataform CLI only (GCP Dataform support pending)."
        }
    ],
    "ActionConfig.DeclarationConfig": [
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the declaration."
        },
        {
            "name": "dataset",
            "type": "string",
            "repeated": false,
            "doc": "The dataset (schema) of the declaration."
        },
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the declaration."
        },
        {
            "name": "description",
            "type": "string",
            "repeated": false,
            "doc": "Description of the declaration."
        },
        {
            "name": "columns",
            "type": "ColumnDescriptor",
            "repeated": true,
            "doc": "Descriptions of columns within the declaration."
        },
        {
            "name": "filename",
            "type": "string",
            "repeated": false,
            "doc": "Path to the source file that the contents of the action is loaded from."
        },
        {
            "name": "tags",
            "type": "string",
            "repeated": true,
            "doc": "A list of user-defined tags with which the action should be labeled."
        }
    ],
    "ActionConfig.NotebookConfig": [
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the notebook."
        },
        {
            "name": "location",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud location of the notebook."
        },
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the notebook."
        },
        {
            "name": "dependencyTargets",
            "type": "Target",
            "repeated": true,
            "doc": "Targets of actions that this action is dependent on."
        },
        {
            "name": "filename",
            "type": "string",
            "repeated": false,
            "doc": "Path to the source file that the contents of the action is loaded from."
        },
        {
            "name": "tags",
            "type": "string",
            "repeated": true,
            "doc": "A list of user-defined tags with which the action should be labeled."
        },
        {
            "name": "disabled",
            "type": "bool",
            "repeated": false,
            "doc": "If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions."
        },
        {
            "name": "description",
            "type": "string",
            "repeated": false,
            "doc": "Description of the notebook."
        },
        {
            "name": "dependOnDependencyAssertions",
            "type": "bool",
            "repeated": false,
            "doc": "When set to true, assertions dependent upon any dependency will be add as dedpendency to this action"
        }
    ],
    "ActionConfig.DataPreparationConfig": [
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the data preparation."
        },
        {
            "name": "dataset",
            "type": "string",
            "repeated": false,
            "doc": "The dataset (schema) of the destination table."
        },
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the destination table."
        },
        {
            "name": "dependencyTargets",
            "type": "Target",
            "repeated": true,
            "doc": "Targets of actions that this action is dependent on."
        },
        {
            "name": "filename",
            "type": "string",
            "repeated": false,
            "doc": "Path to the source file that the contents of the action is loaded from."
        },
        {
            "name": "tags",
            "type": "string",
            "repeated": true,
            "doc": "A list of user-defined tags with which the action should be labeled."
        },
        {
            "name": "disabled",
            "type": "bool",
            "repeated": false,
            "doc": "If set to true, this action will not be executed. However, the action can still be depended upon. Useful for temporarily turning off broken actions."
        },
        {
            "name": "description",
            "type": "string",
            "repeated": false,
            "doc": "Description of the data preparation."
        },
        {
            "name": "errorTable",
            "type": "ErrorTableConfig",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "loadMode",
            "type": "LoadModeConfig",
            "repeated": false,
            "doc": ""
        }
    ],
    "ActionConfig.DataPreparationConfig.ErrorTableConfig": [
        {
            "name": "name",
            "type": "string",
            "repeated": false,
            "doc": "The name of the error table."
        },
        {
            "name": "dataset",
            "type": "string",
            "repeated": false,
            "doc": "The dataset (schema) of the error table."
        },
        {
            "name": "project",
            "type": "string",
            "repeated": false,
            "doc": "The Google Cloud project (database) of the error table."
        },
        {
            "name": "retentionDays",
            "type": "int32",
            "repeated": false,
            "doc": ""
        }
    ],
    "ActionConfig.LoadModeConfig": [
        {
            "name": "mode",
            "type": "LoadMode",
            "repeated": false,
            "doc": ""
        },
        {
            "name": "incrementalColumn",
            "type": "string",
            "repeated": false,
            "doc": "Required when mode is MAXIMUM or UNIQUE"
        },
        {
            "name": "uniqueKey",
            "type": "string",
            "repeated": true,
            "doc": "required when mode is MERGE"
        }
    ],
    "RepositorySnapshotDestinationConfig": [
        {
            "name": "repositorySnapshotUri",
            "type": "string",
            "repeated": false,
            "doc": "Storage URI to upload the repository snapshot to."
        }
    ],
    "NotebookRuntimeOptionsConfig": [
        {
            "name": "outputBucket",
            "type": "string",
            "repeated": false,
            "doc": "Storage bucket to output notebooks to after their execution."
        },
        {
            "name": "runtimeTemplateName",
            "type": "string",
            "repeated": false,
            "doc": "Colab runtime template (https://cloud.google.com/colab/docs/runtimes), from which a runtime is created for notebook executions."
        },
        {
            "name": "repositorySnapshotDestination",
            "type": "RepositorySnapshotDestinationConfig",
            "repeated": false,
            "doc": "Storage URI to upload the snapshot to. For empty URI it defaults to the provided output_bucket."
        }
    ]
};

export const protoEnums: Record<string, ProtoEnumValue[]> = {
    "ActionConfig.IcebergTableConfig.FileFormat": [
        {
            "name": "FILE_FORMAT_UNSPECIFIED",
            "doc": "Default value."
        },
        {
            "name": "PARQUET",
            "doc": "Apache Parquet format."
        }
    ],
    "ActionConfig.OnSchemaChange": [
        {
            "name": "IGNORE",
            "doc": "Ignore any schema changes (default)."
        },
        {
            "name": "FAIL",
            "doc": "Fails if the query would result in a new column(s) being added, deleted, or renamed."
        },
        {
            "name": "EXTEND",
            "doc": "Does not block any new column(s) from being added."
        },
        {
            "name": "SYNCHRONIZE",
            "doc": "Does not block any new column(s) from being added, deleted or renamed."
        }
    ],
    "ActionConfig.IncrementalStrategy": [
        {
            "name": "INCREMENTAL_STRATEGY_UNSPECIFIED",
            "doc": "Strategy is unspecified. Defaults to MERGE if uniqueKey is configured, or APPEND otherwise."
        },
        {
            "name": "INCREMENTAL_STRATEGY_MERGE",
            "doc": "MERGE strategy. Matches rows based on uniqueKey to update existing rows or insert new ones."
        },
        {
            "name": "INCREMENTAL_STRATEGY_INSERT_OVERWRITE",
            "doc": "INSERT_OVERWRITE strategy. Overwrites entire partitions in the target table that are present in the new staging data."
        }
    ],
    "ActionConfig.LoadMode": [
        {
            "name": "REPLACE_TABLE",
            "doc": "Replace existing table (default)."
        },
        {
            "name": "APPEND",
            "doc": "Insert into destination table."
        },
        {
            "name": "MAXIMUM",
            "doc": "Insert only records where the specified column value exceeds the existing maximum value in the destination table."
        },
        {
            "name": "UNIQUE",
            "doc": "Insert only records where the specified column value is not already present in the destination column values."
        },
        {
            "name": "MERGE",
            "doc": "Merge records into the destination table, deduplicating using 1+ unique keys"
        }
    ]
};
