"use client";

import { useState } from "react";
import Link from "next/link";
import {
  ArrowRight,
  Check,
  CheckCircle2,
  Copy,
  Database,
  GitBranch,
  Layers,
  ShieldAlert,
  Sparkles,
  Zap,
  ArrowUpRight,
  ExternalLink,
} from "lucide-react";
import { Button } from "@/components/ui/button";

export function ReleaseHighlight() {
  const [activeTab, setActiveTab] = useState<"defer" | "lineage" | "velocity">("defer");
  const [copiedPrReport, setCopiedPrReport] = useState(false);

  const samplePrReport = `### 📊 Dataform Column Impact Report (Branch vs Prod)
**Target:** \`analytics.fct_player_transfers\`

| Column | Change | Severity | Downstream Readers (Dataplex) |
| :--- | :--- | :--- | :--- |
| \`transfer_fee_cents\` | **DROPPED** | 🚨 BREAKING | \`reporting.monthly_finance_pnl\`, \`dashboards.executive_kpis\` |
| \`player_status\` | \`STRING\` → \`INT64\` | ⚠️ TYPE CHANGE | \`ml_models.player_churn_v2\` |
| \`season_year\` | Unchanged | ✅ SAFE | 4 downstream models |

*Generated by [Dataform Tools for VS Code](https://marketplace.visualstudio.com/items?itemName=ashish10alex.vscode-dataform-tools)*`;

  const handleCopyPrReport = () => {
    navigator.clipboard.writeText(samplePrReport);
    setCopiedPrReport(true);
    setTimeout(() => setCopiedPrReport(false), 2000);
  };

  return (
    <section id="v1-18-0" className="relative isolate mx-auto mt-20 max-w-6xl px-4 sm:px-6 md:mt-28">
      {/* Decorative gradient atmosphere */}
      <div
        className="pointer-events-none absolute -top-12 left-1/2 -z-10 h-96 w-full -translate-x-1/2 rounded-full bg-brand/10 blur-3xl"
        aria-hidden
      />

      {/* Header with Release Badge */}
      <div className="flex flex-col items-start gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <div className="inline-flex items-center gap-2 rounded-full border border-brand/30 bg-brand/10 px-3 py-1 text-xs font-medium text-brand">
            <Sparkles className="h-3.5 w-3.5" />
            <span>Graduation Release · v1.18.0</span>
          </div>
          <h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">
            Develop against prod. Merge without fear.
          </h2>
          <p className="mt-2 max-w-3xl text-balance text-muted-foreground sm:text-base">
            Release 1.18.0 introduces two flagship developer superpowers:{" "}
            <strong className="text-foreground">Defer to Production</strong> for zero-build local development,
            and <strong className="text-foreground">Dataplex Column-Level Lineage &amp; Impact Analysis</strong> to
            catch breaking downstream schema changes before they reach main.
          </p>
        </div>

        <div className="flex shrink-0 gap-2">
          <Button asChild variant="outline" size="sm" className="gap-1.5 font-mono text-xs">
            <Link href="/changelog#v1.18.0">
              Read 1.18.0 Notes
              <ArrowUpRight className="h-3.5 w-3.5" />
            </Link>
          </Button>
        </div>
      </div>

      {/* Tab Switcher */}
      <div className="mt-8 flex flex-wrap gap-2 border-b border-border pb-3">
        <button
          onClick={() => setActiveTab("defer")}
          className={`group flex items-center gap-2 rounded-lg px-3.5 py-2 text-sm font-medium transition-all ${
            activeTab === "defer"
              ? "bg-brand text-brand-foreground shadow-sm"
              : "text-muted-foreground hover:bg-muted hover:text-foreground"
          }`}
        >
          <Database className="h-4 w-4" />
          <span>Defer to Production</span>
          <span className="rounded bg-black/20 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wider text-inherit">
            dbt --defer
          </span>
        </button>

        <button
          onClick={() => setActiveTab("lineage")}
          className={`group flex items-center gap-2 rounded-lg px-3.5 py-2 text-sm font-medium transition-all ${
            activeTab === "lineage"
              ? "bg-brand text-brand-foreground shadow-sm"
              : "text-muted-foreground hover:bg-muted hover:text-foreground"
          }`}
        >
          <Layers className="h-4 w-4" />
          <span>Column Lineage &amp; Impact</span>
          <span className="rounded bg-black/20 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wider text-inherit">
            Dataplex
          </span>
        </button>

        <button
          onClick={() => setActiveTab("velocity")}
          className={`group flex items-center gap-2 rounded-lg px-3.5 py-2 text-sm font-medium transition-all ${
            activeTab === "velocity"
              ? "bg-brand text-brand-foreground shadow-sm"
              : "text-muted-foreground hover:bg-muted hover:text-foreground"
          }`}
        >
          <Zap className="h-4 w-4" />
          <span>Developer Velocity</span>
          <span className="rounded bg-black/20 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-wider text-inherit">
            Engine
          </span>
        </button>
      </div>

      {/* Tab 1: Defer to Production */}
      {activeTab === "defer" && (
        <div className="mt-6 grid gap-8 rounded-2xl border bg-card p-6 shadow-sm lg:grid-cols-[1.1fr_1.3fr] lg:p-8">
          <div className="flex flex-col justify-between space-y-6">
            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <span className="rounded bg-brand/10 px-2 py-0.5 font-mono text-xs font-semibold text-brand">
                  FEATURE 01
                </span>
                <span className="text-xs text-muted-foreground">Like dbt&apos;s --defer for Google Dataform</span>
              </div>
              <h3 className="text-2xl font-semibold tracking-tight">
                Stop waiting for upstream builds in dev
              </h3>
              <p className="text-sm leading-relaxed text-muted-foreground">
                In multi-tier ELT pipelines, building dozens of upstream raw and staging tables in your
                personal sandbox is slow and consumes precious BigQuery slots.
              </p>
              <p className="text-sm leading-relaxed text-muted-foreground">
                <strong className="text-foreground">Defer to Production</strong> automatically reads unbuilt
                upstream dependencies directly from your production datasets during dry runs, query previews,
                compiled SQL views, and workflow runs.
              </p>

              <div className="space-y-2.5 pt-2">
                <div className="flex items-start gap-2.5 text-xs text-muted-foreground">
                  <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-brand" />
                  <span>
                    <strong className="text-foreground">In-Editor Ref Decorations:</strong> Real-time{" "}
                    <code className="rounded bg-muted px-1 py-0.5 font-mono text-brand">→ prod</code> indicators
                    and amber <code className="rounded bg-muted px-1 py-0.5 font-mono text-amber-500">⚠ prod</code>{" "}
                    warnings if an upstream model is modified on your branch.
                  </span>
                </div>
                <div className="flex items-start gap-2.5 text-xs text-muted-foreground">
                  <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-brand" />
                  <span>
                    <strong className="text-foreground">Safe Proxy Views for Runs:</strong> Executes full workflows
                    via labelled ephemeral BigQuery proxy views, so Dataform CLI and API read prod safely through
                    dev names.
                  </span>
                </div>
                <div className="flex items-start gap-2.5 text-xs text-muted-foreground">
                  <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-brand" />
                  <span>
                    <strong className="text-foreground">UDF &amp; Routine Deferral:</strong> Resolves custom JavaScript
                    and SQL procedures across dev and prod environments automatically.
                  </span>
                </div>
              </div>
            </div>

            <div className="rounded-lg border bg-muted/40 p-3.5 font-mono text-xs">
              <p className="text-[11px] text-muted-foreground">// settings.json</p>
              <p className="mt-1 text-foreground">
                <span className="text-brand">&quot;vscode-dataform-tools.deferToProd&quot;</span>: <span className="text-emerald-500">true</span>,
              </p>
              <p className="text-foreground">
                <span className="text-brand">&quot;vscode-dataform-tools.prodCompilerOptions&quot;</span>:{" "}
                <span className="text-amber-500">&quot;--default-database=my-prod-project&quot;</span>
              </p>
            </div>
          </div>

          {/* Visual Code Mockup */}
          <div className="flex flex-col overflow-hidden rounded-xl border bg-zinc-950 font-mono text-xs text-zinc-300 shadow-2xl">
            {/* Editor Window Header */}
            <div className="flex items-center justify-between border-b border-zinc-800 bg-zinc-900/90 px-4 py-2.5 text-zinc-400">
              <div className="flex items-center gap-2">
                <span className="h-2.5 w-2.5 rounded-full bg-red-500/80" />
                <span className="h-2.5 w-2.5 rounded-full bg-yellow-500/80" />
                <span className="h-2.5 w-2.5 rounded-full bg-green-500/80" />
                <span className="ml-2 font-sans text-xs text-zinc-300">0300_MONTHLY_REVENUE.sqlx</span>
              </div>
              <div className="flex items-center gap-1.5 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-2 py-0.5 text-[10px] text-emerald-400">
                <span className="h-1.5 w-1.5 rounded-full bg-emerald-400 animate-pulse" />
                Defer: Active
              </div>
            </div>

            {/* Code Body with Inline Decorations */}
            <div className="relative space-y-1.5 p-4 leading-relaxed overflow-x-auto">
              <div className="text-zinc-500">config &#123; type: &quot;table&quot;, tags: [&quot;finance&quot;] &#125;</div>
              <div className="text-zinc-500"></div>
              <div><span className="text-purple-400">SELECT</span></div>
              <div>&nbsp;&nbsp;o.order_id,</div>
              <div>&nbsp;&nbsp;o.customer_id,</div>
              <div>&nbsp;&nbsp;c.company_name,</div>
              <div>&nbsp;&nbsp;o.gross_amount_usd</div>
              <div className="flex flex-wrap items-center gap-2 bg-zinc-900/40 px-1 py-0.5 rounded">
                <span><span className="text-purple-400">FROM</span> $&#123;ref(<span className="text-amber-300">&quot;stg_orders&quot;</span>)&#125; <span className="text-purple-400">AS</span> o</span>
                <span className="inline-flex items-center gap-1 rounded bg-brand/20 px-2 py-0.5 font-sans text-[11px] font-medium text-brand">
                  <span>→ prod</span>
                  <span className="text-[10px] text-zinc-400">(unbuilt in dev)</span>
                </span>
              </div>
              <div className="flex flex-wrap items-center gap-2 bg-amber-500/5 px-1 py-0.5 rounded border border-amber-500/20">
                <span><span className="text-purple-400">JOIN</span> $&#123;ref(<span className="text-amber-300">&quot;dim_customers&quot;</span>)&#125; <span className="text-purple-400">AS</span> c</span>
                <span className="inline-flex items-center gap-1 rounded bg-amber-500/20 px-2 py-0.5 font-sans text-[11px] font-medium text-amber-300">
                  <ShieldAlert className="h-3 w-3" />
                  <span>⚠ prod (branch modified)</span>
                </span>
              </div>
              <div>&nbsp;&nbsp;<span className="text-purple-400">ON</span> o.customer_id = c.id</div>
            </div>

            {/* Status Bar simulation */}
            <div className="mt-auto flex items-center justify-between border-t border-zinc-800 bg-zinc-900/60 px-4 py-2 text-[11px] text-zinc-400">
              <div className="flex items-center gap-3">
                <span className="flex items-center gap-1 text-brand">
                  <Database className="h-3 w-3" />
                  <span>Defer: Prod (database=prod_dw)</span>
                </span>
                <span className="text-zinc-600">|</span>
                <span className="text-zinc-400">Proxy Views: 0 leftover</span>
              </div>
              <span className="text-zinc-500">BigQuery dry-run: 0 B ($0.00)</span>
            </div>
          </div>
        </div>
      )}

      {/* Tab 2: Column Lineage & Impact */}
      {activeTab === "lineage" && (
        <div className="mt-6 grid gap-8 rounded-2xl border bg-card p-6 shadow-sm lg:grid-cols-[1.1fr_1.3fr] lg:p-8">
          <div className="flex flex-col justify-between space-y-6">
            <div className="space-y-4">
              <div className="flex items-center gap-2">
                <span className="rounded bg-brand/10 px-2 py-0.5 font-mono text-xs font-semibold text-brand">
                  FEATURE 02
                </span>
                <span className="text-xs text-muted-foreground">Dataplex Data Lineage API Integration</span>
              </div>
              <h3 className="text-2xl font-semibold tracking-tight">
                Catch breaking schema changes before opening your PR
              </h3>
              <p className="text-sm leading-relaxed text-muted-foreground">
                Renaming or dropping a column can silently break downstream executive dashboards, scheduled ML models,
                or financial reporting.
              </p>
              <p className="text-sm leading-relaxed text-muted-foreground">
                <strong className="text-foreground">Column Level Lineage &amp; Impact Analysis</strong> compares your
                branch&apos;s compiled definitions against production schemas, identifies dropped or retyped columns,
                and queries Google Cloud Dataplex to trace every affected downstream consumer table and process.
              </p>

              <div className="space-y-2.5 pt-2">
                <div className="flex items-start gap-2.5 text-xs text-muted-foreground">
                  <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-brand" />
                  <span>
                    <strong className="text-foreground">Prod Schema Diff:</strong> Compares column signatures against
                    production tables via <code className="rounded bg-muted px-1 py-0.5 font-mono">prodCompilerOptions</code>.
                  </span>
                </div>
                <div className="flex items-start gap-2.5 text-xs text-muted-foreground">
                  <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-brand" />
                  <span>
                    <strong className="text-foreground">Dataplex Dependency Graph:</strong> Discovers downstream readers
                    (exact copy, transformed, or table level) across multiple BigQuery projects.
                  </span>
                </div>
                <div className="flex items-start gap-2.5 text-xs text-muted-foreground">
                  <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-brand" />
                  <span>
                    <strong className="text-foreground">One-Click PR Markdown:</strong> Generates ready-to-paste impact
                    summaries directly into your GitHub / GitLab Pull Request descriptions.
                  </span>
                </div>
              </div>
            </div>

            <div className="flex items-center gap-3">
              <Button onClick={handleCopyPrReport} variant="outline" size="sm" className="gap-2 text-xs">
                {copiedPrReport ? (
                  <>
                    <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />
                    <span>Copied Markdown!</span>
                  </>
                ) : (
                  <>
                    <Copy className="h-3.5 w-3.5" />
                    <span>Copy Sample PR Markdown Report</span>
                  </>
                )}
              </Button>
            </div>
          </div>

          {/* Lineage & Impact Card Mockup */}
          <div className="flex flex-col overflow-hidden rounded-xl border bg-zinc-950 font-sans text-xs shadow-2xl">
            <div className="flex items-center justify-between border-b border-zinc-800 bg-zinc-900/90 px-4 py-2.5 text-zinc-300">
              <div className="flex items-center gap-2">
                <Layers className="h-4 w-4 text-brand" />
                <span className="font-medium">Column Impact Inspector</span>
                <span className="rounded bg-zinc-800 px-1.5 py-0.5 font-mono text-[10px] text-zinc-400">
                  fct_player_transfers
                </span>
              </div>
              <span className="rounded-full bg-red-500/10 px-2 py-0.5 text-[10px] font-medium text-red-400">
                1 Dropped · 1 Altered
              </span>
            </div>

            <div className="p-4 space-y-3">
              {/* Dropped Column Warning Item */}
              <div className="rounded-lg border border-red-500/30 bg-red-500/5 p-3 space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-red-500/20 px-1.5 py-0.5 font-mono text-[11px] font-semibold text-red-400">
                      - transfer_fee_cents
                    </span>
                    <span className="font-mono text-[10px] text-zinc-400">INT64</span>
                  </div>
                  <span className="rounded bg-red-500/20 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-red-400">
                    Dropped
                  </span>
                </div>
                <div className="border-t border-zinc-800/80 pt-2 text-[11px] text-zinc-400">
                  <p className="font-medium text-zinc-300">Downstream Readers via Dataplex Lineage:</p>
                  <ul className="mt-1 space-y-1 pl-3 text-zinc-400">
                    <li className="flex items-center gap-1.5">
                      <span className="h-1 w-1 rounded-full bg-red-400" />
                      <code className="font-mono text-zinc-300">finance_dw.monthly_pnl_summary</code>
                      <span className="text-[10px] text-zinc-500">(Nightly ELT)</span>
                    </li>
                    <li className="flex items-center gap-1.5">
                      <span className="h-1 w-1 rounded-full bg-red-400" />
                      <code className="font-mono text-zinc-300">marketing_bi.executive_kpi_dashboard</code>
                      <span className="text-[10px] text-zinc-500">(Looker Studio)</span>
                    </li>
                  </ul>
                </div>
              </div>

              {/* Retyped Column Item */}
              <div className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 space-y-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-amber-500/20 px-1.5 py-0.5 font-mono text-[11px] font-semibold text-amber-300">
                      ~ player_status
                    </span>
                    <span className="font-mono text-[10px] text-zinc-400">STRING → INT64</span>
                  </div>
                  <span className="rounded bg-amber-500/20 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-amber-300">
                    Retyped
                  </span>
                </div>
                <div className="border-t border-zinc-800/80 pt-2 text-[11px] text-zinc-400">
                  <p className="font-medium text-zinc-300">Downstream Readers via Dataplex Lineage:</p>
                  <ul className="mt-1 space-y-1 pl-3 text-zinc-400">
                    <li className="flex items-center gap-1.5">
                      <span className="h-1 w-1 rounded-full bg-amber-400" />
                      <code className="font-mono text-zinc-300">data_science.churn_prediction_v2</code>
                    </li>
                  </ul>
                </div>
              </div>

              {/* Safe Columns summary */}
              <div className="flex items-center justify-between rounded-lg border border-zinc-800 bg-zinc-900/40 px-3 py-2 text-zinc-400">
                <span className="flex items-center gap-1.5 text-[11px]">
                  <CheckCircle2 className="h-3.5 w-3.5 text-emerald-500" />
                  <span>14 unchanged columns</span>
                </span>
                <span className="text-[10px] text-emerald-400 font-medium">Safe to deploy</span>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Tab 3: Developer Velocity & Engine */}
      {activeTab === "velocity" && (
        <div className="mt-6 grid gap-6 md:grid-cols-3">
          {/* Card 1: Assertion Badges */}
          <div className="flex flex-col justify-between rounded-2xl border bg-card p-6 shadow-sm">
            <div>
              <div className="flex items-center justify-between">
                <span className="rounded bg-brand/10 px-2 py-0.5 font-mono text-xs font-semibold text-brand">
                  PRECISION
                </span>
                <span className="font-mono text-xs text-muted-foreground">#401</span>
              </div>
              <h3 className="mt-3 text-lg font-semibold tracking-tight">Built-in Assertion Kind Badges</h3>
              <p className="mt-2 text-sm text-muted-foreground">
                Instantly identify assertion rules at a glance in the compiled query panel. Clearly labels
                unique keys, non-null constraints, and custom row conditions.
              </p>

              {/* Visual badges mock */}
              <div className="mt-4 space-y-2 rounded-xl border bg-muted/40 p-3 font-mono text-xs">
                <div className="flex items-center gap-2">
                  <span className="rounded bg-sky-500/20 px-2 py-0.5 font-medium text-sky-400">UNIQUE KEY</span>
                  <span className="text-muted-foreground">order_id</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-purple-500/20 px-2 py-0.5 font-medium text-purple-400">NON NULL</span>
                  <span className="text-muted-foreground">customer_id, created_at</span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="rounded bg-amber-500/20 px-2 py-0.5 font-medium text-amber-400">ROW CONDITION</span>
                  <span className="text-muted-foreground">gross_usd &gt;= 0</span>
                </div>
              </div>
            </div>
            <p className="mt-4 text-xs text-muted-foreground">Available directly in compiled view tabs.</p>
          </div>

          {/* Card 2: Interactive Run Changed Actions */}
          <div className="flex flex-col justify-between rounded-2xl border bg-card p-6 shadow-sm">
            <div>
              <div className="flex items-center justify-between">
                <span className="rounded bg-brand/10 px-2 py-0.5 font-mono text-xs font-semibold text-brand">
                  VELOCITY
                </span>
                <span className="font-mono text-xs text-muted-foreground">#393</span>
              </div>
              <h3 className="mt-3 text-lg font-semibold tracking-tight">Interactive Run Changed Actions</h3>
              <p className="mt-2 text-sm text-muted-foreground">
                Like dbt&apos;s <code className="font-mono text-xs text-foreground">state:modified</code>, run only
                actions whose compiled SQL or materialization changed vs main, with interactive multi-select.
              </p>

              {/* Visual quickpick mock */}
              <div className="mt-4 space-y-1.5 rounded-xl border bg-muted/40 p-3 text-xs">
                <div className="font-mono text-[11px] text-muted-foreground">// QuickPick Multi-Select</div>
                <div className="flex items-center gap-2 font-medium text-foreground">
                  <span className="h-3 w-3 rounded border border-brand bg-brand flex items-center justify-center text-[9px] text-white">✓</span>
                  <span>fct_daily_mrr.sqlx</span>
                  <span className="ml-auto text-[10px] text-brand">modified</span>
                </div>
                <div className="flex items-center gap-2 text-muted-foreground">
                  <span className="h-3 w-3 rounded border border-brand bg-brand flex items-center justify-center text-[9px] text-white">✓</span>
                  <span>dim_users.sqlx</span>
                  <span className="ml-auto text-[10px] text-muted-foreground">downstream</span>
                </div>
              </div>
            </div>
            <p className="mt-4 text-xs text-muted-foreground">Caches merge base compilation by UTC day.</p>
          </div>

          {/* Card 3: Session Persistent Cache & Overhaul */}
          <div className="flex flex-col justify-between rounded-2xl border bg-card p-6 shadow-sm">
            <div>
              <div className="flex items-center justify-between">
                <span className="rounded bg-brand/10 px-2 py-0.5 font-mono text-xs font-semibold text-brand">
                  ENGINE
                </span>
                <span className="font-mono text-xs text-muted-foreground">#388</span>
              </div>
              <h3 className="mt-3 text-lg font-semibold tracking-tight">Sub-Second Startup &amp; Caching</h3>
              <p className="mt-2 text-sm text-muted-foreground">
                Fingerprinted CLI compilations now persist across VS Code sessions, completely eliminating cold-start
                delays on editor open.
              </p>

              {/* Performance metric mockup */}
              <div className="mt-4 grid grid-cols-2 gap-2 text-center">
                <div className="rounded-xl border bg-muted/40 p-3">
                  <div className="text-2xl font-bold text-brand">&lt; 0.8s</div>
                  <div className="text-[11px] text-muted-foreground">Quiet Startup</div>
                </div>
                <div className="rounded-xl border bg-muted/40 p-3">
                  <div className="text-2xl font-bold text-emerald-500">0 ms</div>
                  <div className="text-[11px] text-muted-foreground">Cached Recompiles</div>
                </div>
              </div>
            </div>
            <p className="mt-4 text-xs text-muted-foreground">Includes BigQuery auth auto-recovery &amp; VSIX trimming.</p>
          </div>
        </div>
      )}
    </section>
  );
}
