on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      preRelease:
        description: 'Publish as a pre-release'
        required: true
        type: boolean
        default: false

name: Deploy extension to marketplace
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          preRelease: ${{ github.event.inputs.preRelease == 'true' }}
          dryRun: ${{ github.event_name != 'workflow_dispatch' }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          extensionFile: ${{ steps.publishToOpenVSX.outputs.vsixPath }}
          preRelease: ${{ github.event.inputs.preRelease == 'true' }}
          dryRun: ${{ github.event_name != 'workflow_dispatch' }}